GET http://127.0.0.1:8000/validate/IPDE0JQEyEy_jsF9HmkSaw

###

POST http://127.0.0.1:8000/validate/batch
Content-Type: application/json

[
  "WAdsqd2QHkyTAkAXZ1Am9A",
  "gmbcWFZsEUWwSld3_frKwA",
  "IPDE0JQEyEy_jsF9HmkSaw"
]